name: dama_common
description: A starting point for Dart libraries or applications.
version: 1.0.2
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.13.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
